// In-memory filesystem factory.
export function buildFS() {
  return {
    "/": { type: "dir", children: ["home", "root", "etc", "var", "tmp", "usr", "bin", "dev", "proc"] },
    "/home": { type: "dir", children: ["kali"] },
    "/home/kali": { type: "dir", children: ["Desktop", "Documents", "Downloads", ".bashrc"] },
    "/home/kali/Desktop": { type: "dir", children: [] },
    "/home/kali/Documents": { type: "dir", children: ["notes.txt", "readme.md"] },
    "/home/kali/Documents/notes.txt": { type: "file", content: "Remember to patch systems.\nHack the planet.\n" },
    "/home/kali/Documents/readme.md": { type: "file", content: "# Kali Linux Simulator\n\nWelcome to the Kali Linux terminal simulator.\nType `help` to see all commands.\n" },
    "/home/kali/Downloads": { type: "dir", children: [] },
    "/home/kali/.bashrc": { type: "file", content: "# ~/.bashrc\nexport TERM=xterm-256color\nexport EDITOR=nano\n" },
    "/root": { type: "dir", children: ["Desktop", "Documents", "tools", ".bashrc", ".profile"] },
    "/root/Desktop": { type: "dir", children: ["README.txt"] },
    "/root/Desktop/README.txt": { type: "file", content: "Welcome to Kali Linux Simulator!\n\nThis is a sandboxed environment.\nType 'help' for available commands.\n\nHappy hacking!\n" },
    "/root/Documents": { type: "dir", children: ["targets.txt", "wordlist.txt", "report.txt"] },
    "/root/Documents/targets.txt": { type: "file", content: "192.168.1.1\n192.168.1.100\n10.0.0.1\n172.16.0.5\n" },
    "/root/Documents/wordlist.txt": { type: "file", content: "admin\npassword\n123456\nroot\ntoor\nkali\nletmein\nqwerty\nmaster\ndragon\n" },
    "/root/Documents/report.txt": { type: "file", content: "Penetration Test Report\n========================\nDate: 2024-03-31\nTarget: 192.168.1.0/24\n\nFindings:\n- Port 22 (SSH) open on 192.168.1.100\n- Port 80 (HTTP) open on 192.168.1.100\n- Weak credentials found: admin/admin\n" },
    "/root/tools": { type: "dir", children: ["exploit.py", "scanner.sh"] },
    "/root/tools/exploit.py": { type: "file", content: "#!/usr/bin/env python3\n# Basic port scanner\nimport socket\n\ntarget = '192.168.1.100'\nfor port in range(20, 1025):\n    s = socket.socket()\n    s.settimeout(0.5)\n    if s.connect_ex((target, port)) == 0:\n        print(f'Port {port} is open')\n    s.close()\n" },
    "/root/tools/scanner.sh": { type: "file", content: "#!/bin/bash\n# Quick network scanner\nfor i in $(seq 1 254); do\n  ping -c1 -W1 192.168.1.$i &>/dev/null && echo \"192.168.1.$i is up\"\ndone\n" },
    "/root/.bashrc": { type: "file", content: "# ~/.bashrc\nexport PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\nexport TERM=xterm-256color\nexport HISTSIZE=1000\nalias ll='ls -la'\nalias la='ls -A'\nalias grep='grep --color=auto'\n" },
    "/root/.profile": { type: "file", content: "# ~/.profile\nif [ -n \"$BASH_VERSION\" ]; then\n  [ -f \"$HOME/.bashrc\" ] && . \"$HOME/.bashrc\"\nfi\n" },
    "/etc": { type: "dir", children: ["passwd", "shadow", "hosts", "hostname", "os-release", "network", "apt"] },
    "/etc/passwd": { type: "file", content: "root:x:0:0:root:/root:/bin/bash\nkali:x:1000:1000:Kali,,,:/home/kali:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nwww-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\n" },
    "/etc/shadow": { type: "file", content: "root:$6$rounds=656000$kali$abc123:18765:0:99999:7:::\nkali:$6$rounds=656000$kali$def456:18765:0:99999:7:::\n" },
    "/etc/hosts": { type: "file", content: "127.0.0.1\tlocalhost\n127.0.1.1\tkali\n::1\t\tlocalhost ip6-localhost\n192.168.1.100\ttarget.local\n192.168.1.1\tgateway.local\n" },
    "/etc/hostname": { type: "file", content: "kali\n" },
    "/etc/os-release": { type: "file", content: "NAME=\"Kali GNU/Linux\"\nVERSION=\"2024.1\"\nID=kali\nID_LIKE=debian\nPRETTY_NAME=\"Kali GNU/Linux 2024.1 (Rolling)\"\nVERSION_ID=\"2024.1\"\nHOME_URL=\"https://www.kali.org/\"\nSUPPORT_URL=\"https://bugs.kali.org/\"\n" },
    "/etc/network": { type: "dir", children: ["interfaces"] },
    "/etc/network/interfaces": { type: "file", content: "auto lo\niface lo inet loopback\n\nauto eth0\niface eth0 inet dhcp\n" },
    "/etc/apt": { type: "dir", children: ["sources.list"] },
    "/etc/apt/sources.list": { type: "file", content: "deb http://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware\n" },
    "/var": { type: "dir", children: ["log", "www", "tmp"] },
    "/var/log": { type: "dir", children: ["syslog", "auth.log", "kern.log"] },
    "/var/log/syslog": { type: "file", content: "Mar 31 10:00:01 kali kernel: Linux version 6.6.9-amd64\nMar 31 10:00:02 kali systemd[1]: Starting system...\nMar 31 10:00:05 kali sshd[1234]: Server listening on 0.0.0.0 port 22\nMar 31 10:05:12 kali kernel: eth0: renamed from veth3a2f1b\n" },
    "/var/log/auth.log": { type: "file", content: "Mar 31 10:15:32 kali sshd[2341]: Accepted password for root from 192.168.1.50\nMar 31 10:16:00 kali sudo: root : TTY=pts/0\nMar 31 10:20:11 kali sshd[2891]: Failed password for admin from 192.168.1.200\n" },
    "/var/log/kern.log": { type: "file", content: "Mar 31 10:00:01 kali kernel: [0.000000] Linux version 6.6.9-amd64\nMar 31 10:00:01 kali kernel: [0.000000] BIOS-provided physical RAM map\nMar 31 10:00:01 kali kernel: [0.004000] ACPI: IRQ0 used by override\n" },
    "/var/www": { type: "dir", children: ["html"] },
    "/var/www/html": { type: "dir", children: ["index.html"] },
    "/var/www/html/index.html": { type: "file", content: "<!DOCTYPE html>\n<html>\n<head><title>Apache2 Default Page</title></head>\n<body><h1>It works!</h1></body>\n</html>\n" },
    "/var/tmp": { type: "dir", children: [] },
    "/tmp": { type: "dir", children: [] },
    "/usr": { type: "dir", children: ["bin", "share", "local"] },
    "/usr/bin": { type: "dir", children: ["nmap", "python3", "curl", "wget", "john", "hydra", "metasploit", "aircrack-ng", "burpsuite", "wireshark"] },
    "/usr/bin/nmap": { type: "file", content: "[binary]" },
    "/usr/bin/python3": { type: "file", content: "[binary]" },
    "/usr/bin/curl": { type: "file", content: "[binary]" },
    "/usr/bin/wget": { type: "file", content: "[binary]" },
    "/usr/bin/john": { type: "file", content: "[binary]" },
    "/usr/bin/hydra": { type: "file", content: "[binary]" },
    "/usr/bin/metasploit": { type: "file", content: "[binary]" },
    "/usr/bin/aircrack-ng": { type: "file", content: "[binary]" },
    "/usr/bin/burpsuite": { type: "file", content: "[binary]" },
    "/usr/bin/wireshark": { type: "file", content: "[binary]" },
    "/usr/share": { type: "dir", children: ["wordlists", "nmap"] },
    "/usr/share/wordlists": { type: "dir", children: ["rockyou.txt"] },
    "/usr/share/wordlists/rockyou.txt": { type: "file", content: "password\n123456\n12345678\nqwerty\nabc123\nmonkey\n1234567\nletmein\ntrusted\ndragon\nmaster\nsunshine\nprincess\nwelcome\nshadow\n" },
    "/usr/share/nmap": { type: "dir", children: ["scripts"] },
    "/usr/share/nmap/scripts": { type: "dir", children: [] },
    "/usr/local": { type: "dir", children: ["bin", "share"] },
    "/usr/local/bin": { type: "dir", children: [] },
    "/usr/local/share": { type: "dir", children: [] },
    "/bin": { type: "dir", children: ["bash", "sh", "ls", "cat", "cp", "mv", "rm", "mkdir", "echo", "grep", "find"] },
    "/dev": { type: "dir", children: ["null", "zero", "tty", "sda", "sda1"] },
    "/dev/null": { type: "file", content: "" },
    "/dev/zero": { type: "file", content: "" },
    "/proc": { type: "dir", children: ["version", "cpuinfo", "meminfo", "net"] },
    "/proc/version": { type: "file", content: "Linux version 6.6.9-amd64 (devel@kali.org) (gcc version 13.2.0) #1 SMP PREEMPT_DYNAMIC Kali 6.6.9-1kali1 (2024-01-08)\n" },
    "/proc/cpuinfo": { type: "file", content: "processor\t: 0\nvendor_id\t: GenuineIntel\ncpu family\t: 6\nmodel name\t: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz\ncpu MHz\t\t: 2600.000\ncache size\t: 12288 KB\nbogomips\t: 5200.00\n" },
    "/proc/meminfo": { type: "file", content: "MemTotal:\t 8192000 kB\nMemFree:\t 5234816 kB\nMemAvailable:\t 6298624 kB\nBuffers:\t  512000 kB\nCached:\t\t 1024000 kB\nSwapTotal:\t 2097152 kB\nSwapFree:\t 2097152 kB\n" },
    "/proc/net": { type: "dir", children: ["arp", "dev"] },
    "/proc/net/arp": { type: "file", content: "IP address       HW type     Flags       HW address            Mask     Device\n192.168.1.1      0x1         0x2         aa:bb:cc:dd:ee:01     *        eth0\n192.168.1.100    0x1         0x2         aa:bb:cc:dd:ee:64     *        eth0\n" },
    "/proc/net/dev": { type: "file", content: "Inter-|   Receive                                                |  Transmit\n face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets\n    lo:  123456    1000    0    0    0     0          0         0   123456    1000\n  eth0: 2134921    4523    0    0    0     0          0         0   984721    3211\n" },
  };
}
